# Generated by Django 4.2.5 on 2023-10-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('role', models.CharField(default='None', max_length=20)),
                ('password', models.CharField(default='123', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Username', models.CharField(default='None', max_length=30, unique=True)),
                ('Password', models.CharField(default='123', max_length=100)),
                ('subjects', models.CharField(default='None', max_length=100)),
                ('grades', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
