# Generated by Django 4.2.5 on 2023-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Master',
        ),
    ]
