# Generated by Django 4.2.5 on 2023-10-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_rename_admin_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='role',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
